# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Niels Oeltjen
email: niels@nielsoeltjen.com
description: Artist and design technologist. Contact me here, and other places.
baseurl: ""
url: "http://nielsoeltjen.com/"
github_username:  Elbone

profiles:
  instagram: "https://instagram.com/nielsoeltjen/"
  folio: "https://elbone.github.io/"
  github: "https://github.com/elbone/"
  twitter: "https://twitter.com/nielsoeltjen"


# Build settings
markdown: kramdown
sass:
  style: compressed
